version: "3"

services:
  frontend:
    container_name: mrwerk
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mrwerk.rule=Host(`www.mr-werk-iserlohn.de`)"
      - "traefik.http.routers.mrwerk.entrypoints=https"
      - "traefik.http.routers.mrwerk.tls.certresolver=httpresolver"
      - "traefik.docker.network=traefik_network"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
